**<h3>DSCI 510: Principles of Programming for Data Science </h3>**
<h4>Spring 2023 – Assignment 7</h4>

Instructor: <a href="mailto:ambite@isi.edu">Prof. Jose Luis Ambite </a>                       				                           
Course Producers: <a href="mailto:svara@usc.edu">Samuel Vara</a>, <a href="mailto:svparakh@usc.edu">Sanjana Parakh</a>, <a href="mailto:swarnita@usc.edu">Swarnita Venkatraman</a>, <a href="mailto:gursimar@usc.edu">Gursimar Kaur</a>
</h2>

**Guidelines for the Assignment:**

- You have to complete the assignments individually. If you are having trouble completing the assignment do let the TAs know/post on Piazza.

- Please don't copy code (either partially/fully) from your classmates. Plagiarism of any form will result in a 0 and you will be reported to SJACS (https://sjacs.usc.edu/students/academic-integrity/).

- You have to fill the code in this notebook and upload it for submission. While doing this, make sure all supporting files that you download from D2L are in the same directory as this notebook.  

- File Naming Convention : Lab7_LastName_FirstName.ipynb

- Don't change existing methods (if any, unless otherwise mentioned in the instructions)

- You are encouraged to look up resources online like python docs and stackoverflow. Look up the topics and not the questions themselves. 

- Your last submission before the deadline will be counted towards your grade. You can submit any number of times before the deadline.

- You need to take input from file/console only if it is mentioned in the question. If not we need just the logic/implementation of your function.

- Scores are capped at 10 points including the Bonus problem. For Example: Even if you get a score of 12/10, your score is capped at 10.

- Bonus score is counted only if the first 2 questions are attempted. Don't attempt the bonus question if you haven't attempted the first 2.

----------------------------------------------

**Question 1 [3 points]**

Create a Employee class with the followinng properties and methods.

Class Variables = (Initial value)
- employee_count = 0 - integer
- high_earning_employees = []  - list (of Employee objects) - those earning greater than $5000

Instance Variables = (Initial value)
....must be inside dunder init
- first_name - string
- last_name - string
- company - string
- salary - float ->
if salary > $5000:
    add the created object to class variable "high_earning_employees"

if Employee object is successfully created increment employee_count

class dunder functions
*   str
*   repr

Instance method
* fullname() = first_name [space] last_name

Do not add functions/variables other than the ones above.






In [1]:
# WRITE YOUR CLASS BELOW
class Employee():
    employee_count = 0
    high_earning_employees = [] 
    def __init__(self, first_name:str, last_name:str, company:str, salary:float)->None:
        self.first_name = first_name
        self.last_name = last_name
        self.company = company
        self.salary = salary
        Employee.employee_count +=1
        if self.salary > 5000:
            Employee.high_earning_employees.append(self)
            
    def fullname(self):
        return '{} {}'.format\
    (self.first_name,self.last_name)
    
    def __str__(self):
        return f'Employee: {self.first_name} {self.last_name} at {self.company} earning ${self.salary}'
    
    def __repr__(self):
        return f'<{self.__class__.__name__} (first_name={self.first_name!r}, last_name={self.last_name!r}, company={self.company!r}, salary={self.salary})>'
        

Question 2 [3 points]

Create Employee objects for using data from each line in employees_raw_data.txt . Add each of these objects to "employees_list" list. Print employees_list (which should trigger dunder str of each Employee object)

In [2]:
employees_list = []
file = open(r'./employees_raw_data.txt', 'r')
lines_ls = file.readlines()
for val in range(len(lines_ls)-1):
    vals = lines_ls[val].rstrip().split(',')[0].split(' ') + lines_ls[val].rstrip().split(',')[1:]
    first_n, last_n, comp, salary = vals[0], vals[1], vals[2], float(vals[3].split('$')[1])
    employees_list.append(Employee(first_n, last_n, comp, salary))
    
[str(val1) for val1 in employees_list]

['Employee: Jeffrey Fauna at AT&T earning $10000.0',
 'Employee: Rey Odin at Delta earning $20000.0',
 'Employee: Ceibhfhionn Grid at Tinder earning $40000.0',
 'Employee: E Bile at Karl Lagerfeld earning $10000.0',
 'Employee: Oissine Malta at Gap earning $2000.0']

Question 3 [4 points]

Complete the function "check". Your code should Go through each Employee object and check if there is a part of an attribute (first_name, last_name, company) value that matches that query term. If a match does exists, return all such Employee object (use dunder str) else return an empty list. [Case insensitive]

Return type - list of strings
[Hint: Use str.find()]

Example 1

Employee1
 - first_name = Jeffrey
 - last_name = Daniels
 - company = Amazon
 - wage = 10000

Employee2
 - first_name = Jeff
 - last_name = Hubert
 - company = Google
 - wage = 20000

Employee3
 - first_name = Roger
 - last_name = Foggle
 - company = Tinder
 - wage = 30000



query - "eff"

returns
["Employee: Jeffrey Daniels at Amazon earning 10000.0", "Employee: Jeff Hubert at Google earning 20000.0"]

'eff' in "Jeffrey" and "Jeff"

query - "gle"

returns
["Employee: Roger Foggle at Tinder earning 30000.0", "Employee: Jeff Hubert at Google earning 20000.0"]

'gle' in "Google" and "Foggle"

In [289]:
def check(query):
    return_ls = [] 
    for clas in employees_list:
        t = [clas.first_name, clas.last_name, clas.company, clas.salary]
        for element in t[:-1]:
            if query in element:
                return_ls.append(str(clas))
    return return_ls

In [290]:
print(check('er'))
print(check('lta'))

['Employee: Ceibhfhionn Grid at Tinder earning $40000.0', 'Employee: E Bile at Karl Lagerfeld earning $10000.0']
['Employee: Rey Odin at Delta earning $20000.0', 'Employee: Oissine Malta at Gap earning $2000.0']


**Bonus Question [1 point]**

Print the unique identifier for each object in employees list (use id()) and the identifier's hex code (use hex()). <br>
Write a code to get the number of Employee objects created using the class variable employee_count and get all the High Earning Employee details (Hint: Use dunder str)

In [68]:
# Unique Identifier
for index in range(len(employees_list)):
    print('Object #', index+1, ': ' ,id(employees_list[index]), index+1, '-',hex(id(employees_list[index])), sep = '',)

print('Number of employees:', Employee.employee_count)
[str(val) for val in Employee.high_earning_employees]

Object #1: 1405619588489761-0x7fd721a049d0
Object #2: 1405619589399042-0x7fd721a1ad00
Object #3: 1405619589406243-0x7fd721a1afd0
Object #4: 1405619589399524-0x7fd721a1ad30
Object #5: 1405619589401445-0x7fd721a1adf0
Number of employees: 5


['Employee: Jeffrey Fauna at AT&T earning $10000.0',
 'Employee: Rey Odin at Delta earning $20000.0',
 'Employee: Ceibhfhionn Grid at Tinder earning $40000.0',
 'Employee: E Bile at Karl Lagerfeld earning $10000.0']

In [3]:
def my_function(a, b, *args, **kwargs):
    print(a, b, args, kwargs)
    
my_function(1,2,3,4,5,6, c=2, d=3)

1 2 (3, 4, 5, 6) {'c': 2, 'd': 3}


In [5]:
b = set('bananna!')
p = set('papaya')
p.symmetric_difference(b)
b&p, b.intersection(p), b-p, p-b

({'a'}, {'a'}, {'!', 'b', 'n'}, {'p', 'y'})

In [19]:
x = {'bannanna', 'bannanna'*2}
x

{'bannanna', 'bannannabannanna'}